@startuml Phonebook
title Phonebook

class Phonebook
{
	- all_contact: Contact[8]
	- contact_counts: int
	+ add()
	+ search()
}

class Contact
{
	- first_name: String
	- last_name: String
	- nickname: String
	- phone_number: String
	- darkest_secret: String
}

Phonebook "1" o-- "0..8" Contact : "contains"

@enduml